org.gradle.jvmargs=-Xmx3G
org.gradle.daemon=false

minecraft_version=1.21.1
minecraft_version_range=[1.21.1,1.22)
neo_version=21.1.72
neo_version_range=[21.1,)
loader_version_range=[2,)

mod_id=pvpnight
mod_name=PvP Night
mod_license=MIT
mod_version=1.0.0
mod_authors=PvPNight Dev
mod_description=Weekly PvP day mod. PvP is disabled except for one day every 7 game days.

maven_group=com.pvpnight
archives_base_name=pvpnight
