modLoader = "javafml"
loaderVersion = "${loader_version_range}"
license = "${mod_license}"

[[mods]]
    modId = "pvpnight"
    version = "${mod_version}"
    displayName = "PvP Night"
    description = "Weekly PvP day mod. PvP is disabled except for one day every 7 game days."

[[dependencies.pvpnight]]
    modId = "neoforge"
    type = "required"
    versionRange = "${neo_version_range}"
    ordering = "NONE"
    side = "BOTH"

[[dependencies.pvpnight]]
    modId = "minecraft"
    type = "required"
    versionRange = "${minecraft_version_range}"
    ordering = "NONE"
    side = "BOTH"
